// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VaccinationCenter.Data;

#nullable disable

namespace VaccinationCenter.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("VaccinationCenter.Models.Addresse", b =>
                {
                    b.Property<int>("AdresseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CodePostal")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Rue")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("AdresseId");

                    b.ToTable("Adresses");
                });

            modelBuilder.Entity("VaccinationCenter.Models.CentreVaccination", b =>
                {
                    b.Property<int>("CentreVaccinationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NbChaises")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NumTelephone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponsableCentre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("CentreVaccinationId");

                    b.ToTable("CentresVaccination");

                    b.HasData(
                        new
                        {
                            CentreVaccinationId = 1,
                            Capacite = 500,
                            NbChaises = 50,
                            NumTelephone = 74123456,
                            ResponsableCentre = "Dr. Ahmed Ben Ali"
                        },
                        new
                        {
                            CentreVaccinationId = 2,
                            Capacite = 300,
                            NbChaises = 30,
                            NumTelephone = 74654321,
                            ResponsableCentre = "Dr. Fatma Triki"
                        });
                });

            modelBuilder.Entity("VaccinationCenter.Models.Citoyen", b =>
                {
                    b.Property<int>("CiToyenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AdresseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CIN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("NumeroEvax")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Telephone")
                        .HasColumnType("INTEGER");

                    b.HasKey("CiToyenId");

                    b.HasIndex("AdresseId");

                    b.HasIndex("CIN")
                        .IsUnique();

                    b.HasIndex("NumeroEvax")
                        .IsUnique();

                    b.ToTable("Citoyens");
                });

            modelBuilder.Entity("VaccinationCenter.Models.Compte", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Login")
                        .IsUnique();

                    b.ToTable("Comptes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Login = "admin",
                            Password = "$2a$11$pXUAnqgR07cDjU9TuYbAWekKzptmBYTSfPNWRocg1S2EomwuqS3R.",
                            Role = "Admin"
                        });
                });

            modelBuilder.Entity("VaccinationCenter.Models.RendezVous", b =>
                {
                    b.Property<int>("RendezVousId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CiToyenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodeInfirmiere")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DateVaccination")
                        .HasColumnType("TEXT");

                    b.Property<int>("NbrDoses")
                        .HasColumnType("INTEGER");

                    b.Property<int>("VaccinId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RendezVousId");

                    b.HasIndex("CiToyenId");

                    b.HasIndex("VaccinId");

                    b.ToTable("RendezVous");
                });

            modelBuilder.Entity("VaccinationCenter.Models.Vaccin", b =>
                {
                    b.Property<int>("VaccinId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CentreVaccinationId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateValidite")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fournisseur")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TypeVaccin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("VaccinId");

                    b.HasIndex("CentreVaccinationId");

                    b.ToTable("Vaccins");

                    b.HasData(
                        new
                        {
                            VaccinId = 1,
                            CentreVaccinationId = 1,
                            DateValidite = new DateTime(2026, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fournisseur = "Pfizer Inc.",
                            Quantite = 1000,
                            TypeVaccin = "PFizer"
                        },
                        new
                        {
                            VaccinId = 2,
                            CentreVaccinationId = 1,
                            DateValidite = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fournisseur = "Moderna Inc.",
                            Quantite = 500,
                            TypeVaccin = "Moderna"
                        },
                        new
                        {
                            VaccinId = 3,
                            CentreVaccinationId = 2,
                            DateValidite = new DateTime(2025, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Fournisseur = "Johnson & Johnson",
                            Quantite = 300,
                            TypeVaccin = "Jhonson"
                        });
                });

            modelBuilder.Entity("VaccinationCenter.Models.Citoyen", b =>
                {
                    b.HasOne("VaccinationCenter.Models.Addresse", "Addresse")
                        .WithMany("Citoyens")
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Addresse");
                });

            modelBuilder.Entity("VaccinationCenter.Models.RendezVous", b =>
                {
                    b.HasOne("VaccinationCenter.Models.Citoyen", "Citoyen")
                        .WithMany("RendezVous")
                        .HasForeignKey("CiToyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VaccinationCenter.Models.Vaccin", "Vaccin")
                        .WithMany("RendezVous")
                        .HasForeignKey("VaccinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Citoyen");

                    b.Navigation("Vaccin");
                });

            modelBuilder.Entity("VaccinationCenter.Models.Vaccin", b =>
                {
                    b.HasOne("VaccinationCenter.Models.CentreVaccination", "CentreVaccination")
                        .WithMany("Vaccins")
                        .HasForeignKey("CentreVaccinationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CentreVaccination");
                });

            modelBuilder.Entity("VaccinationCenter.Models.Addresse", b =>
                {
                    b.Navigation("Citoyens");
                });

            modelBuilder.Entity("VaccinationCenter.Models.CentreVaccination", b =>
                {
                    b.Navigation("Vaccins");
                });

            modelBuilder.Entity("VaccinationCenter.Models.Citoyen", b =>
                {
                    b.Navigation("RendezVous");
                });

            modelBuilder.Entity("VaccinationCenter.Models.Vaccin", b =>
                {
                    b.Navigation("RendezVous");
                });
#pragma warning restore 612, 618
        }
    }
}
